apiVersion: apps/v1
kind: Deployment
metadata:
  name: eum-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eum-api
  template:
    metadata:
      labels:
        app: eum-api
    spec:
      containers:
      - name: eum-api
        image: kimchanghyun/eum-api:k8s
        env:
        - name: TZ
          value: "Asia/Seoul"
        - name: CENTER_DB_IP
          value: "center-db"
        - name: CENTER_DB_PORT
          value: "3306"
        - name: CENTER_DB_USER
          value: "admin"
        - name: CENTER_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: password    
        - name: EUM_DB_IP
          value: "eum-db"
        - name: EUM_DB_PORT
          value: "3306"
        - name: EUM_DB_USER
          value: "admin"
        - name: EUM_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: password
        ports:
        - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: eum-api
spec:
  selector:
    app: eum-api
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eum-api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: 
    http:
      paths:
      - pathType: Prefix
        path: /eum/
        backend:
          service:
            name: eum-api-1
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: eum-api-1
spec:
  selector:
    app: eum-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9091
