apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: surffy
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: nks-nas-csi
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: center-loader-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: center-loader-core
  template:
    metadata:
      labels:
        app: center-loader-core
    spec:
      containers:
        - name: center-loader-core
          image: kimchanghyun/center-loader-core:k8s
          env:
            - name: TZ
              value: Asia/Seoul
            - name: DB_IP
              value: center-db
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password      
          ports:
          - containerPort: 12000
          volumeMounts:
          - name: data-volume
            mountPath: /datasurfer
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: surffy
---
apiVersion: v1
kind: Service
metadata:
  name: center-loader-core
spec:
  selector:
    app: center-loader-core
  ports:
    - protocol: TCP
      port: 12000
      targetPort: 12000
